import { Worker } from './models/worker';

/** Company-wide contact address. */
const CONTACT_EMAIL = 'nile.tech.africa.development@gmail.com';

/**
 * The team. No backend — this is the single source of truth, served from memory.
 * History is ordered most-recent first so the timeline reads top (now) to bottom (start).
 */
export const TEAM: readonly Worker[] = [
  {
    id: 'dominic-atari-obiala',
    name: 'Dominic Atari Obiala',
    role: 'Founder · Software Architect',
    tagline: 'From a spreadsheet in Kakuma to software architecture.',
    location: 'Juba, South Sudan',
    initials: 'DO',
    accent: 'violet',
    bio: "Dominic's path into software started with a spreadsheet in a refugee camp. From Kakuma to Lincoln, Nebraska, he went from tracking a food business in Excel to shipping real products — and now leads architecture at Nile Tech, designing the IDesign way in C# and building across Java, Angular, and Ionic.",
    focus: ['C#', 'IDesign method', 'Java', 'HTML / CSS / JS', 'TypeScript', 'Angular', 'Ionic'],
    email: CONTACT_EMAIL,
    links: [
      { label: 'GitHub', href: 'https://github.com/' },
      { label: 'LinkedIn', href: 'https://www.linkedin.com/' },
    ],
    history: [
      {
        year: '2026 – now',
        title: 'Founder & Software Architect',
        org: 'Nile Tech Solutions',
        description: 'Designs systems for a living now — the same instinct that started with a spreadsheet in Kakuma, applied with the IDesign method in C# and built across Java, Angular, and Ionic.',
        kind: 'milestone',
        current: true,
      },
      {
        year: '2026',
        title: 'Pathways Program Graduate',
        org: "Don't Panic Labs",
        description: 'Twenty weeks that turned a self-taught builder into an engineer. He showed up, did the work, and walked out ready to make a team better.',
        kind: 'education',
      },
      {
        year: '2025',
        title: 'Building Anchovy',
        org: 'TMCO',
        description: "Diane, TMCO's CEO, backed him to build Anchovy — a mobile app for saving and organizing recipes. His first real product, made for real people.",
        kind: 'role',
      },
      {
        year: '2024',
        title: 'Java & Spring Boot',
        org: 'Southeast Community College · Lincoln, NE',
        description: 'Enrolled at SCC and got serious about software — learning Java and writing his first Spring Boot applications.',
        kind: 'education',
      },
      {
        year: '2023',
        title: 'A fresh start in the United States',
        org: 'Lincoln, Nebraska',
        description: 'Arriving in the US, he made a decision: no more working around problems in a spreadsheet. It was time to build real software.',
        kind: 'milestone',
      },
      {
        year: 'Until 2023',
        title: 'Bamba Chakula shop owner',
        org: 'Kakuma Refugee Camp, Kenya',
        description: 'Ran a Bamba Chakula food business in the camp. As customer records piled up, he taught himself to keep track of it all in Microsoft Excel — the first time technology solved a real problem for him. The spark.',
        kind: 'milestone',
      },
    ],
  },
  {
    id: 'george-isaac-gum',
    name: 'George Isaac Gum',
    role: 'Co-founder · Marketing Lead',
    tagline: 'Gets the work in front of the right people.',
    location: 'Berlin, DE',
    initials: 'GG',
    accent: 'teal',
    bio: "George leads how Nile Tech shows up in the world — brand, positioning, and growth. More than five years leading marketing teams taught him that even the best engineering still needs someone who can tell its story.",
    focus: ['Brand strategy', 'Growth marketing', 'Team leadership', 'Go-to-market', 'Content', 'Analytics'],
    email: CONTACT_EMAIL,
    links: [
      { label: 'LinkedIn', href: 'https://www.linkedin.com/' },
      { label: 'X', href: 'https://x.com/' },
    ],
    history: [
      {
        year: '2023 – now',
        title: 'Co-founder & Marketing Lead',
        org: 'Nile Tech Solutions',
        description: "Owns brand, positioning, and growth — turning the studio's engineering work into a story clients actually hear.",
        kind: 'milestone',
        current: true,
      },
      {
        year: '2021 – 2023',
        title: 'Head of Marketing',
        org: 'Cobalt Health',
        description: 'Led a marketing team of eight through two product launches, building the brand and the demand engine behind them.',
        kind: 'role',
      },
      {
        year: '2019 – 2021',
        title: 'Marketing Manager',
        org: 'Fathom',
        description: 'Stepped into leadership — owned campaigns end to end and grew the team from two to five.',
        kind: 'role',
      },
      {
        year: '2016 – 2019',
        title: 'Growth Marketer',
        org: 'Studio Verso',
        description: 'Cut his teeth on content and paid growth for a long list of demanding clients.',
        kind: 'role',
      },
      {
        year: '2016',
        title: 'B.A. Marketing & Communications',
        org: 'University of the Arts London',
        description: 'Where the storytelling started.',
        kind: 'education',
      },
    ],
  },
  {
    id: 'amara-nwosu',
    name: 'Amara Nwosu',
    role: 'Senior Backend Engineer',
    tagline: 'Keeps the systems underneath honest.',
    location: 'Remote · Lagos, NG',
    initials: 'AN',
    accent: 'violet',
    bio: 'Amara owns the services and schemas that everything else depends on. She likes the unglamorous work — migrations, indexes, and error paths — because that is where products quietly succeed or fail.',
    focus: ['Node.js', 'Python', 'Postgres', 'APIs', 'Observability'],
    email: CONTACT_EMAIL,
    links: [
      { label: 'GitHub', href: 'https://github.com/' },
      { label: 'LinkedIn', href: 'https://www.linkedin.com/' },
    ],
    history: [
      {
        year: '2022 – now',
        title: 'Senior Backend Engineer',
        org: 'Nile Tech Solutions',
        description: 'Builds and hardens the platform layer across client projects — the APIs, jobs, and data models that carry the load.',
        kind: 'role',
        current: true,
      },
      {
        year: '2019 – 2022',
        title: 'Backend Engineer',
        org: 'Paystack',
        description: 'Shipped payments and reconciliation services at scale, where correctness and uptime were the whole job.',
        kind: 'role',
      },
      {
        year: '2017 – 2019',
        title: 'Software Engineer',
        org: 'Andela',
        description: 'Worked across a rotation of client teams — a fast way to learn how many different ways a codebase can go wrong.',
        kind: 'role',
      },
      {
        year: '2017',
        title: 'B.Sc. Software Engineering',
        org: 'University of Lagos',
        description: 'Started on the backend and never really left.',
        kind: 'education',
      },
    ],
  },
  {
    id: 'lucas-meyer',
    name: 'Lucas Meyer',
    role: 'Frontend Engineer',
    tagline: 'Sweats the last ten percent.',
    location: 'Lisbon, PT',
    initials: 'LM',
    accent: 'teal',
    bio: "Lucas turns designs into interfaces that feel right — fast, accessible, and consistent down to the focus ring. He's happiest closing the gap between what a mock promises and what the browser delivers.",
    focus: ['Angular', 'TypeScript', 'CSS', 'Accessibility', 'Performance'],
    email: CONTACT_EMAIL,
    links: [
      { label: 'GitHub', href: 'https://github.com/' },
      { label: 'LinkedIn', href: 'https://www.linkedin.com/' },
    ],
    history: [
      {
        year: '2022 – now',
        title: 'Frontend Engineer',
        org: 'Nile Tech Solutions',
        description: 'Builds the client-facing app across projects and keeps the component library sharp as products grow.',
        kind: 'role',
        current: true,
      },
      {
        year: '2020 – 2022',
        title: 'Frontend Developer',
        org: 'Unbabel',
        description: 'Owned key surfaces of a real-time translation product, tuning them for speed and for users under pressure.',
        kind: 'role',
      },
      {
        year: '2018 – 2020',
        title: 'Junior Developer',
        org: 'Bright Pixel',
        description: 'First job out of school. Learned the craft by shipping small things carefully.',
        kind: 'role',
      },
      {
        year: '2018',
        title: 'B.Sc. Computer Science',
        org: 'Instituto Superior Técnico',
        description: 'Fell for the front end when a professor said it was the easy part.',
        kind: 'education',
      },
    ],
  },
  {
    id: 'priya-nair',
    name: 'Priya Nair',
    role: 'Product Designer',
    tagline: 'Draws the line before the code does.',
    location: 'Bangalore, IN',
    initials: 'PN',
    accent: 'violet',
    bio: 'Priya shapes what the product should be before a line of it is written — flows, prototypes, and the hard questions about what to leave out. She designs in the same tokens the team builds in.',
    focus: ['Product design', 'Figma', 'Prototyping', 'Research', 'Design systems'],
    email: CONTACT_EMAIL,
    links: [
      { label: 'Portfolio', href: 'https://example.com/' },
      { label: 'LinkedIn', href: 'https://www.linkedin.com/' },
    ],
    history: [
      {
        year: '2023 – now',
        title: 'Product Designer',
        org: 'Nile Tech Solutions',
        description: 'Owns discovery and interface design across engagements, working shoulder to shoulder with the engineers building it.',
        kind: 'role',
        current: true,
      },
      {
        year: '2020 – 2023',
        title: 'UX Designer',
        org: 'Freshworks',
        description: 'Designed core workflows for a product used by tens of thousands of businesses, and learned to defend simplicity.',
        kind: 'role',
      },
      {
        year: '2017 – 2020',
        title: 'Visual Designer',
        org: 'Lollypop Studio',
        description: 'Cut her teeth on brand and interface work for a long list of very particular clients.',
        kind: 'role',
      },
      {
        year: '2017',
        title: 'B.Des. Communication Design',
        org: 'National Institute of Design',
        description: 'Where the habit of asking "why this at all?" started.',
        kind: 'education',
      },
    ],
  },
  {
    id: 'tomas-herrera',
    name: 'Tomás Herrera',
    role: 'Platform & DevOps Engineer',
    tagline: 'Makes shipping boring, on purpose.',
    location: 'Madrid, ES',
    initials: 'TH',
    accent: 'teal',
    bio: 'Tomás owns the path from a commit to production — pipelines, infrastructure, and the alerts that wake someone up. His goal is that a deploy is the least interesting thing that happens all day.',
    focus: ['Kubernetes', 'Terraform', 'CI/CD', 'AWS', 'Reliability'],
    email: CONTACT_EMAIL,
    links: [
      { label: 'GitHub', href: 'https://github.com/' },
      { label: 'LinkedIn', href: 'https://www.linkedin.com/' },
    ],
    history: [
      {
        year: '2022 – now',
        title: 'Platform & DevOps Engineer',
        org: 'Nile Tech Solutions',
        description: 'Builds the delivery and infrastructure layer for every client — repeatable, observable, and hard to break.',
        kind: 'role',
        current: true,
      },
      {
        year: '2019 – 2022',
        title: 'DevOps Engineer',
        org: 'Cabify',
        description: 'Ran infrastructure for high-traffic services and cut deploy times from hours to minutes.',
        kind: 'role',
      },
      {
        year: '2016 – 2019',
        title: 'Systems Engineer',
        org: 'Telefónica',
        description: 'Learned reliability the old-fashioned way — on systems that were never allowed to go down.',
        kind: 'role',
      },
      {
        year: '2016',
        title: 'B.Sc. Computer Engineering',
        org: 'Universidad Politécnica de Madrid',
        description: 'Started automating things so he could stop repeating them.',
        kind: 'education',
      },
    ],
  },
];
