import { Worker } from './models/worker';

/**
 * The team. No backend — this is the single source of truth, served from memory.
 * History is ordered most-recent first so the timeline reads top (now) to bottom (start).
 */
export const TEAM: readonly Worker[] = [
  {
    id: 'dominic-atari-obiala',
    name: 'Dominic Atari Obiala',
    role: 'Founder · Principal Engineer',
    tagline: 'Turns tangled systems into straight lines.',
    location: 'London, UK',
    initials: 'DO',
    accent: 'violet',
    bio: 'Dominic builds the parts of a product that have to stay standing at 3am — payment flows, data pipelines, the schema everything else leans on. He started Line to do that work without the layers in between.',
    focus: ['Distributed systems', 'TypeScript', 'Go', 'Postgres', 'Platform design'],
    email: 'dominic@linetech.solutions',
    links: [
      { label: 'GitHub', href: 'https://github.com/' },
      { label: 'LinkedIn', href: 'https://www.linkedin.com/' },
    ],
    history: [
      {
        year: '2023 – now',
        title: 'Founder & Principal Engineer',
        org: 'Line Tech Solutions',
        description: 'Founded the studio to ship production systems for a handful of clients at a time, end to end, with no hand-offs.',
        kind: 'milestone',
        current: true,
      },
      {
        year: '2020 – 2023',
        title: 'Staff Engineer',
        org: 'Northgate Payments',
        description: 'Owned the ledger and settlement platform through a 30× volume increase. Led the migration off a monolith without a single day of downtime.',
        kind: 'role',
      },
      {
        year: '2017 – 2020',
        title: 'Senior Backend Engineer',
        org: 'Meridian',
        description: 'Worked on the data platform behind personalization — the pipelines that turned billions of events into something the product could read in milliseconds.',
        kind: 'role',
      },
      {
        year: '2014 – 2017',
        title: 'Software Engineer',
        org: 'Klarna',
        description: 'Cut his teeth on risk and checkout services where a wrong number meant real money. Learned to write code that fails loudly, not quietly.',
        kind: 'role',
      },
      {
        year: '2014',
        title: 'M.Sc. Computer Science',
        org: 'Imperial College London',
        description: 'Thesis on fault-tolerant stream processing. First line of the throughline.',
        kind: 'education',
      },
    ],
  },
  {
    id: 'george-isaac-gum',
    name: 'George Isaac Gum',
    role: 'Co-founder · Design Engineer',
    tagline: 'Lives on the line between design and code.',
    location: 'Berlin, DE',
    initials: 'GG',
    accent: 'teal',
    bio: 'George makes the product you actually touch — interfaces that feel obvious in the hand and hold up under real use. He treats a design system like an API: small, consistent, and hard to misuse.',
    focus: ['Design systems', 'Angular', 'Motion', 'Accessibility', 'Prototyping'],
    email: 'george@linetech.solutions',
    links: [
      { label: 'GitHub', href: 'https://github.com/' },
      { label: 'Dribbble', href: 'https://dribbble.com/' },
    ],
    history: [
      {
        year: '2023 – now',
        title: 'Co-founder & Design Engineer',
        org: 'Line Tech Solutions',
        description: 'Leads everything the client sees — from the first prototype to the shipped front end — and keeps design and code in sync.',
        kind: 'milestone',
        current: true,
      },
      {
        year: '2021 – 2023',
        title: 'Design Systems Lead',
        org: 'Cobalt Health',
        description: 'Built the component library and tokens used across six product teams. Shipped a full theming layer and cut UI review time roughly in half.',
        kind: 'role',
      },
      {
        year: '2018 – 2021',
        title: 'Product Engineer',
        org: 'Fathom',
        description: 'An early engineer. Owned the front end from a blank repo to a product used daily by thousands of teams.',
        kind: 'role',
      },
      {
        year: '2015 – 2018',
        title: 'Frontend Developer',
        org: 'Studio Verso',
        description: 'Built interactive sites for brands who cared about the last 10%. Learned that motion is a language, not decoration.',
        kind: 'role',
      },
      {
        year: '2015',
        title: 'B.A. Interaction Design',
        org: 'University of the Arts London',
        description: 'Where the design half of design engineer came from.',
        kind: 'education',
      },
    ],
  },
  {
    id: 'amara-nwosu',
    name: 'Amara Nwosu',
    role: 'Senior Backend Engineer',
    tagline: 'Keeps the systems underneath honest.',
    location: 'Remote · Lagos, NG',
    initials: 'AN',
    accent: 'violet',
    bio: 'Amara owns the services and schemas that everything else depends on. She likes the unglamorous work — migrations, indexes, and error paths — because that is where products quietly succeed or fail.',
    focus: ['Node.js', 'Python', 'Postgres', 'APIs', 'Observability'],
    email: 'amara@linetech.solutions',
    links: [
      { label: 'GitHub', href: 'https://github.com/' },
      { label: 'LinkedIn', href: 'https://www.linkedin.com/' },
    ],
    history: [
      {
        year: '2022 – now',
        title: 'Senior Backend Engineer',
        org: 'Line Tech Solutions',
        description: 'Builds and hardens the platform layer across client projects — the APIs, jobs, and data models that carry the load.',
        kind: 'role',
        current: true,
      },
      {
        year: '2019 – 2022',
        title: 'Backend Engineer',
        org: 'Paystack',
        description: 'Shipped payments and reconciliation services at scale, where correctness and uptime were the whole job.',
        kind: 'role',
      },
      {
        year: '2017 – 2019',
        title: 'Software Engineer',
        org: 'Andela',
        description: 'Worked across a rotation of client teams — a fast way to learn how many different ways a codebase can go wrong.',
        kind: 'role',
      },
      {
        year: '2017',
        title: 'B.Sc. Software Engineering',
        org: 'University of Lagos',
        description: 'Started on the backend and never really left.',
        kind: 'education',
      },
    ],
  },
  {
    id: 'lucas-meyer',
    name: 'Lucas Meyer',
    role: 'Frontend Engineer',
    tagline: 'Sweats the last ten percent.',
    location: 'Lisbon, PT',
    initials: 'LM',
    accent: 'teal',
    bio: "Lucas turns designs into interfaces that feel right — fast, accessible, and consistent down to the focus ring. He's happiest closing the gap between what a mock promises and what the browser delivers.",
    focus: ['Angular', 'TypeScript', 'CSS', 'Accessibility', 'Performance'],
    email: 'lucas@linetech.solutions',
    links: [
      { label: 'GitHub', href: 'https://github.com/' },
      { label: 'LinkedIn', href: 'https://www.linkedin.com/' },
    ],
    history: [
      {
        year: '2022 – now',
        title: 'Frontend Engineer',
        org: 'Line Tech Solutions',
        description: 'Builds the client-facing app across projects and keeps the component library sharp as products grow.',
        kind: 'role',
        current: true,
      },
      {
        year: '2020 – 2022',
        title: 'Frontend Developer',
        org: 'Unbabel',
        description: 'Owned key surfaces of a real-time translation product, tuning them for speed and for users under pressure.',
        kind: 'role',
      },
      {
        year: '2018 – 2020',
        title: 'Junior Developer',
        org: 'Bright Pixel',
        description: 'First job out of school. Learned the craft by shipping small things carefully.',
        kind: 'role',
      },
      {
        year: '2018',
        title: 'B.Sc. Computer Science',
        org: 'Instituto Superior Técnico',
        description: 'Fell for the front end when a professor said it was the easy part.',
        kind: 'education',
      },
    ],
  },
  {
    id: 'priya-nair',
    name: 'Priya Nair',
    role: 'Product Designer',
    tagline: 'Draws the line before the code does.',
    location: 'Bangalore, IN',
    initials: 'PN',
    accent: 'violet',
    bio: 'Priya shapes what the product should be before a line of it is written — flows, prototypes, and the hard questions about what to leave out. She designs in the same tokens the team builds in.',
    focus: ['Product design', 'Figma', 'Prototyping', 'Research', 'Design systems'],
    email: 'priya@linetech.solutions',
    links: [
      { label: 'Portfolio', href: 'https://example.com/' },
      { label: 'LinkedIn', href: 'https://www.linkedin.com/' },
    ],
    history: [
      {
        year: '2023 – now',
        title: 'Product Designer',
        org: 'Line Tech Solutions',
        description: 'Owns discovery and interface design across engagements, working shoulder to shoulder with the engineers building it.',
        kind: 'role',
        current: true,
      },
      {
        year: '2020 – 2023',
        title: 'UX Designer',
        org: 'Freshworks',
        description: 'Designed core workflows for a product used by tens of thousands of businesses, and learned to defend simplicity.',
        kind: 'role',
      },
      {
        year: '2017 – 2020',
        title: 'Visual Designer',
        org: 'Lollypop Studio',
        description: 'Cut her teeth on brand and interface work for a long list of very particular clients.',
        kind: 'role',
      },
      {
        year: '2017',
        title: 'B.Des. Communication Design',
        org: 'National Institute of Design',
        description: 'Where the habit of asking "why this at all?" started.',
        kind: 'education',
      },
    ],
  },
  {
    id: 'tomas-herrera',
    name: 'Tomás Herrera',
    role: 'Platform & DevOps Engineer',
    tagline: 'Makes shipping boring, on purpose.',
    location: 'Madrid, ES',
    initials: 'TH',
    accent: 'teal',
    bio: 'Tomás owns the path from a commit to production — pipelines, infrastructure, and the alerts that wake someone up. His goal is that a deploy is the least interesting thing that happens all day.',
    focus: ['Kubernetes', 'Terraform', 'CI/CD', 'AWS', 'Reliability'],
    email: 'tomas@linetech.solutions',
    links: [
      { label: 'GitHub', href: 'https://github.com/' },
      { label: 'LinkedIn', href: 'https://www.linkedin.com/' },
    ],
    history: [
      {
        year: '2022 – now',
        title: 'Platform & DevOps Engineer',
        org: 'Line Tech Solutions',
        description: 'Builds the delivery and infrastructure layer for every client — repeatable, observable, and hard to break.',
        kind: 'role',
        current: true,
      },
      {
        year: '2019 – 2022',
        title: 'DevOps Engineer',
        org: 'Cabify',
        description: 'Ran infrastructure for high-traffic services and cut deploy times from hours to minutes.',
        kind: 'role',
      },
      {
        year: '2016 – 2019',
        title: 'Systems Engineer',
        org: 'Telefónica',
        description: 'Learned reliability the old-fashioned way — on systems that were never allowed to go down.',
        kind: 'role',
      },
      {
        year: '2016',
        title: 'B.Sc. Computer Engineering',
        org: 'Universidad Politécnica de Madrid',
        description: 'Started automating things so he could stop repeating them.',
        kind: 'education',
      },
    ],
  },
];
